apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  namespace: default
spec:
  selector:
    app: vproapp
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: vproapp-port
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can spLoadBalanceralue in the `spec.ports[*].nodePort` field.
